---
- name: Create Flannel download directory
  file:
    path: "{{ flannel_download_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0701'

- name: Download Flannel tar file
  get_url:
    url: "{{ flannel_release_url }}"  
    dest: "{{ flannel_download_dir }}"
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"

- name: Set Flannel tar file permissions
  file:
    path: "{{ flannel_download_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
    state: file
    owner: apache
    group: apache
    mode: '0701'
