---
- name: Create Kubernetes download directory
  file:
    path: "{{ kube_download_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0701'

- name: Download Kubernetes binaries
  get_url:
    url: "{{ kube_release_url_base }}{{ item }}"
    dest: "{{ kube_download_dir }}/{{ item }}"
    mode: 0755
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  with_items:
    - "{{ kube_binaries }}"

- name: Set Kubernetes binaries permissions
  file:
    path: "{{ kube_download_dir }}/{{ item }}"
    state: file
    owner: apache
    group: apache
    mode: '0701'
  with_items: 
    - "{{ kube_binaries }}"
