---
- name: Create PyPy download directory
  file:
    path: "{{ pypy_download_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0701'

- name: Download PyPy tar file
  get_url:
    url: "{{ pypy_release_url }}"
    dest: "{{ pypy_download_dir }}"
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"

- name: Set PyPy binary permissions
  file:
    path: "{{ pypy_download_dir }}/pypy-{{ pypy_version }}-linux64.tar.bz2"
    state: file
    owner: apache
    group: apache
    mode: '0701'
