---
- name: Determine if PyPy download directory exists
  stat: path={{ pypy_download_dir }}
  register: ppdd
  changed_when: false
  always_run: yes

- name: Create PyPy download directory
  file: path={{ pypy_download_dir }} state=directory
  when: not ppdd.stat.exists

- name: Determine if PyPy tar file exists
  stat: path={{ pypy_download_dir }}/pypy-{{ pypy_version }}-linux64.tar.bz2
  register: ppt
  changed_when: false
  always_run: yes

- name: Download PyPy tar file
  get_url:
    url: "https://bitbucket.org/pypy/pypy/downloads/pypy-{{ pypy_version }}-linux64.tar.bz2"
    dest: "{{ pypy_download_dir }}"
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  when: not ppt.stat.exists
